// Constants for creating an account
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

// Constants for getting accounts by user
export const GET_ACCOUNTS_BY_USER_REQUEST = 'GET_ACCOUNTS_BY_USER_REQUEST';
export const GET_ACCOUNTS_BY_USER_SUCCESS = 'GET_ACCOUNTS_BY_USER_SUCCESS';
export const GET_ACCOUNTS_BY_USER_FAILURE = 'GET_ACCOUNTS_BY_USER_FAILURE';

// Constants for getting all accounts
export const GET_ALL_ACCOUNTS_REQUEST = 'GET_ALL_ACCOUNTS_REQUEST';
export const GET_ALL_ACCOUNTS_SUCCESS = 'GET_ALL_ACCOUNTS_SUCCESS';
export const GET_ALL_ACCOUNTS_FAILURE = 'GET_ALL_ACCOUNTS_FAILURE';

// Constants for getting an account by UUID
export const GET_ACCOUNT_BY_UUID_REQUEST = 'GET_ACCOUNT_BY_UUID_REQUEST';
export const GET_ACCOUNT_BY_UUID_SUCCESS = 'GET_ACCOUNT_BY_UUID_SUCCESS';
export const GET_ACCOUNT_BY_UUID_FAILURE = 'GET_ACCOUNT_BY_UUID_FAILURE';

// Constants for deleting an account
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
