// brokerConstants.js

export const CREATE_BROKER_REQUEST = 'CREATE_BROKER_REQUEST';
export const CREATE_BROKER_SUCCESS = 'CREATE_BROKER_SUCCESS';
export const CREATE_BROKER_FAILURE = 'CREATE_BROKER_FAILURE';

export const GET_ALL_BROKERS_REQUEST = 'GET_ALL_BROKERS_REQUEST';
export const GET_ALL_BROKERS_SUCCESS = 'GET_ALL_BROKERS_SUCCESS';
export const GET_ALL_BROKERS_FAILURE = 'GET_ALL_BROKERS_FAILURE';

export const GET_BROKER_BY_ID_REQUEST = 'GET_BROKER_BY_ID_REQUEST';
export const GET_BROKER_BY_ID_SUCCESS = 'GET_BROKER_BY_ID_SUCCESS';
export const GET_BROKER_BY_ID_FAILURE = 'GET_BROKER_BY_ID_FAILURE';

export const DELETE_BROKER_REQUEST = 'DELETE_BROKER_REQUEST';
export const DELETE_BROKER_SUCCESS = 'DELETE_BROKER_SUCCESS';
export const DELETE_BROKER_FAILURE = 'DELETE_BROKER_FAILURE';

export const UPDATE_BROKER_REQUEST = 'UPDATE_BROKER_REQUEST';
export const UPDATE_BROKER_SUCCESS = 'UPDATE_BROKER_SUCCESS';
export const UPDATE_BROKER_FAILURE = 'UPDATE_BROKER_FAILURE';
