// Credit Action Types
export const CREATE_CREDIT_REQUEST = 'CREATE_CREDIT_REQUEST';
export const CREATE_CREDIT_SUCCESS = 'CREATE_CREDIT_SUCCESS';
export const CREATE_CREDIT_FAILURE = 'CREATE_CREDIT_FAILURE';

export const GET_ALL_CREDITS_REQUEST = 'GET_ALL_CREDITS_REQUEST';
export const GET_ALL_CREDITS_SUCCESS = 'GET_ALL_CREDITS_SUCCESS';
export const GET_ALL_CREDITS_FAILURE = 'GET_ALL_CREDITS_FAILURE';

export const GET_CREDIT_BY_UUID_REQUEST = 'GET_CREDIT_BY_UUID_REQUEST';
export const GET_CREDIT_BY_UUID_SUCCESS = 'GET_CREDIT_BY_UUID_SUCCESS';
export const GET_CREDIT_BY_UUID_FAILURE = 'GET_CREDIT_BY_UUID_FAILURE';

export const DELETE_CREDIT_REQUEST = 'DELETE_CREDIT_REQUEST';
export const DELETE_CREDIT_SUCCESS = 'DELETE_CREDIT_SUCCESS';
export const DELETE_CREDIT_FAILURE = 'DELETE_CREDIT_FAILURE';

export const GET_CREDITS_BY_USER_REQUEST = 'GET_CREDITS_BY_USER_REQUEST';
export const GET_CREDITS_BY_USER_SUCCESS = 'GET_CREDITS_BY_USER_SUCCESS';
export const GET_CREDITS_BY_USER_FAILURE = 'GET_CREDITS_BY_USER_FAILURE';
