// referralConstants.js

export const CREATE_REFERRAL_REQUEST = 'CREATE_REFERRAL_REQUEST';
export const CREATE_REFERRAL_SUCCESS = 'CREATE_REFERRAL_SUCCESS';
export const CREATE_REFERRAL_FAILURE = 'CREATE_REFERRAL_FAILURE';

export const GET_ALL_REFERRALS_REQUEST = 'GET_ALL_REFERRALS_REQUEST';
export const GET_ALL_REFERRALS_SUCCESS = 'GET_ALL_REFERRALS_SUCCESS';
export const GET_ALL_REFERRALS_FAILURE = 'GET_ALL_REFERRALS_FAILURE';

export const GET_REFERRAL_BY_ID_REQUEST = 'GET_REFERRAL_BY_ID_REQUEST';
export const GET_REFERRAL_BY_ID_SUCCESS = 'GET_REFERRAL_BY_ID_SUCCESS';
export const GET_REFERRAL_BY_ID_FAILURE = 'GET_REFERRAL_BY_ID_FAILURE';

export const DELETE_REFERRAL_REQUEST = 'DELETE_REFERRAL_REQUEST';
export const DELETE_REFERRAL_SUCCESS = 'DELETE_REFERRAL_SUCCESS';
export const DELETE_REFERRAL_FAILURE = 'DELETE_REFERRAL_FAILURE';

export const UPDATE_REFERRAL_REQUEST = 'UPDATE_REFERRAL_REQUEST';
export const UPDATE_REFERRAL_SUCCESS = 'UPDATE_REFERRAL_SUCCESS';
export const UPDATE_REFERRAL_FAILURE = 'UPDATE_REFERRAL_FAILURE';
