// brokerConstants.js

export const CREATE_SERVER_REQUEST = 'CREATE_SERVER_REQUEST';
export const CREATE_SERVER_SUCCESS = 'CREATE_SERVER_SUCCESS';
export const CREATE_SERVER_FAILURE = 'CREATE_SERVER_FAILURE';

export const GET_ALL_SERVERS_REQUEST = 'GET_ALL_SERVERS_REQUEST';
export const GET_ALL_SERVERS_SUCCESS = 'GET_ALL_SERVERS_SUCCESS';
export const GET_ALL_SERVERS_FAILURE = 'GET_ALL_SERVERS_FAILURE';

export const GET_SERVER_BY_ID_REQUEST = 'GET_SERVER_BY_ID_REQUEST';
export const GET_SERVER_BY_ID_SUCCESS = 'GET_SERVER_BY_ID_SUCCESS';
export const GET_SERVER_BY_ID_FAILURE = 'GET_SERVER_BY_ID_FAILURE';

export const DELETE_SERVER_REQUEST = 'DELETE_SERVER_REQUEST';
export const DELETE_SERVER_SUCCESS = 'DELETE_SERVER_SUCCESS';
export const DELETE_SERVER_FAILURE = 'DELETE_SERVER_FAILURE';

export const UPDATE_SERVER_REQUEST = 'UPDATE_SERVER_REQUEST';
export const UPDATE_SERVER_SUCCESS = 'UPDATE_SERVER_SUCCESS';
export const UPDATE_SERVER_FAILURE = 'UPDATE_SERVER_FAILURE';

export const GET_SERVERS_BY_BROKER_REQUEST = 'GET_SERVERS_BY_BROKER_REQUEST';
export const GET_SERVERS_BY_BROKER_SUCCESS = 'GET_SERVERS_BY_BROKER_SUCCESS';
export const GET_SERVERS_BY_BROKER_FAILURE = 'GET_SERVERS_BY_BROKER_FAILURE';

