name: Node.js CI

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          # Deployment commands for dev environment
          # Replace with the actual commands to deploy to dev

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/prod'
        run: |
          # Deployment commands for prod environment
          # Replace with the actual commands to deploy to prod
